// Mengambil aset dari folder public/Icon di dalam proyek React
const ICON_DIR = '/Icon';

// DAFTAR 89 LAYANAN TERKATEGORI
export const AVAILABLE_SERVICES = [
  { id: 'srv-1', name: 'Patreon', category: 'Social', url: 'https://www.patreon.com', iconPath: `${ICON_DIR}/patreon.ico` },
  { id: 'srv-2', name: 'PayPal', category: 'Productivity', url: 'https://www.paypal.com', iconPath: `${ICON_DIR}/paypal.ico` },
  { id: 'srv-3', name: 'Pinterest', category: 'Social', url: 'https://www.pinterest.com', iconPath: `${ICON_DIR}/pinterest.ico` },
  { id: 'srv-4', name: '500px', category: 'Media', url: 'https://500px.com', iconPath: `${ICON_DIR}/px.ico` },
  { id: 'srv-5', name: 'Quora', category: 'Social', url: 'https://www.quora.com', iconPath: `${ICON_DIR}/quora.ico` },
  { id: 'srv-6', name: 'Reddit', category: 'Social', url: 'https://www.reddit.com', iconPath: `${ICON_DIR}/reddit.ico` },
  { id: 'srv-7', name: 'RSS Feed', category: 'Media', url: 'https://rss.com', iconPath: `${ICON_DIR}/rss.ico` },
  { id: 'srv-8', name: 'Safari', category: 'Productivity', url: 'https://www.apple.com/safari/', iconPath: `${ICON_DIR}/safari.ico` },
  { id: 'srv-9', name: 'Skype', category: 'Messaging', url: 'https://web.skype.com', iconPath: `${ICON_DIR}/skype.ico` },
  { id: 'srv-10', name: 'Slack', category: 'Messaging', url: 'https://app.slack.com', iconPath: `${ICON_DIR}/slack.ico` },
  { id: 'srv-11', name: 'Snapchat', category: 'Messaging', url: 'https://web.snapchat.com', iconPath: `${ICON_DIR}/snapchat.ico` },
  { id: 'srv-12', name: 'SoundCloud', category: 'Media', url: 'https://soundcloud.com', iconPath: `${ICON_DIR}/soundcloud.ico` },
  { id: 'srv-14', name: 'Stack Overflow', category: 'Development', url: 'https://stackoverflow.com', iconPath: `${ICON_DIR}/stack-overflow.ico` },
  { id: 'srv-15', name: 'Steam', category: 'Media', url: 'https://store.steampowered.com', iconPath: `${ICON_DIR}/steam.ico` },
  { id: 'srv-16', name: 'Telegram', category: 'Messaging', url: 'https://web.telegram.org/a/', iconPath: `${ICON_DIR}/telegram.ico` },
  { id: 'srv-17', name: 'Threads', category: 'Social', url: 'https://www.threads.net', iconPath: `${ICON_DIR}/threads.ico` },
  { id: 'srv-18', name: 'TikTok', category: 'Social', url: 'https://www.tiktok.com', iconPath: `${ICON_DIR}/tiktok.ico` },
  { id: 'srv-19', name: 'Tribars', category: 'Other', url: 'https://example.com', iconPath: `${ICON_DIR}/tribars.ico` },
  { id: 'srv-20', name: 'Tumblr', category: 'Social', url: 'https://www.tumblr.com', iconPath: `${ICON_DIR}/tumblr.ico` },
  { id: 'srv-21', name: 'Twitch', category: 'Media', url: 'https://m.twitch.tv', iconPath: `${ICON_DIR}/twitch.ico` },
  { id: 'srv-22', name: 'Twitter', category: 'Social', url: 'https://x.com', iconPath: `${ICON_DIR}/twitter.ico` },
  { id: 'srv-23', name: 'Ubuntu', category: 'Development', url: 'https://ubuntu.com', iconPath: `${ICON_DIR}/ubuntu.ico` },
  { id: 'srv-24', name: 'Vimeo', category: 'Media', url: 'https://vimeo.com', iconPath: `${ICON_DIR}/vimeo.ico` },
  { id: 'srv-25', name: 'VK', category: 'Social', url: 'https://m.vk.com', iconPath: `${ICON_DIR}/vk.ico` },
  { id: 'srv-26', name: 'WeChat', category: 'Messaging', url: 'https://web.wechat.com', iconPath: `${ICON_DIR}/wechat.ico` },
  { id: 'srv-27', name: 'WhatsApp', category: 'Messaging', url: 'https://web.whatsapp.com', iconPath: `${ICON_DIR}/whatsapp.ico`, isNativeLauncher: true, packageName: 'com.whatsapp' },
  { id: 'srv-28', name: 'Wikipedia', category: 'Productivity', url: 'https://m.wikipedia.org', iconPath: `${ICON_DIR}/wikipedia.ico` },
  { id: 'srv-29', name: 'WordPress', category: 'Development', url: 'https://wordpress.com', iconPath: `${ICON_DIR}/wordpress.ico` },
  { id: 'srv-30', name: 'X', category: 'Social', url: 'https://x.com', iconPath: `${ICON_DIR}/x.ico` },
  { id: 'srv-31', name: 'Yelp', category: 'Other', url: 'https://m.yelp.com', iconPath: `${ICON_DIR}/yelp.ico` },
  { id: 'srv-32', name: 'YouTube', category: 'Media', url: 'https://m.youtube.com', iconPath: `${ICON_DIR}/youtube.ico`, isNativeLauncher: true, packageName: 'com.google.android.youtube' },
  { id: 'srv-33', name: 'Apple', category: 'Productivity', url: 'https://www.apple.com', iconPath: `${ICON_DIR}/apple.ico` },
  { id: 'srv-34', name: 'Behance', category: 'Social', url: 'https://www.behance.net', iconPath: `${ICON_DIR}/behance.ico` },
  { id: 'srv-35', name: 'Bing', category: 'Productivity', url: 'https://www.bing.com', iconPath: `${ICON_DIR}/bing.ico` },
  { id: 'srv-36', name: 'Bitbucket', category: 'Development', url: 'https://bitbucket.org', iconPath: `${ICON_DIR}/bitbucket.ico` },
  { id: 'srv-37', name: 'Blogger', category: 'Media', url: 'https://www.blogger.com', iconPath: `${ICON_DIR}/blogger.ico` },
  { id: 'srv-38', name: 'Bluesky', category: 'Social', url: 'https://bsky.app', iconPath: `${ICON_DIR}/bluesky.ico` },
  { id: 'srv-39', name: 'CC BY', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-by.ico` },
  { id: 'srv-40', name: 'CC CC', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-cc.ico` },
  { id: 'srv-41', name: 'CC NC', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-nc.ico` },
  { id: 'srv-42', name: 'CC NC EU', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-nc-eu.ico` },
  { id: 'srv-43', name: 'CC NC JP', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-nc-jp.ico` },
  { id: 'srv-44', name: 'CC ND', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-nd.ico` },
  { id: 'srv-45', name: 'CC PD', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-pd.ico` },
  { id: 'srv-46', name: 'CC Remix', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-remix.ico` },
  { id: 'srv-47', name: 'CC SA', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-sa.ico` },
  { id: 'srv-48', name: 'CC Sampling', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-sampling.ico` },
  { id: 'srv-49', name: 'CC Sampling+', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-sampling-plus.ico` },
  { id: 'srv-50', name: 'CC Share', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-share.ico` },
  { id: 'srv-51', name: 'CC Zero', category: 'Creative Commons', url: 'https://creativecommons.org', iconPath: `${ICON_DIR}/cc-zero.ico` },
  { id: 'srv-52', name: 'Chrome', category: 'Browser', url: 'https://www.google.com', iconPath: `${ICON_DIR}/chrome.ico`, isBrowser: true },
  { id: 'srv-53', name: 'CodePen', category: 'Development', url: 'https://codepen.io', iconPath: `${ICON_DIR}/codepen.ico` },
  { id: 'srv-54', name: 'CSS3', category: 'Development', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS', iconPath: `${ICON_DIR}/css3.ico` },
  { id: 'srv-55', name: 'CSS3 Box', category: 'Development', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS', iconPath: `${ICON_DIR}/css3-box.ico` },
  { id: 'srv-56', name: 'DeviantArt', category: 'Social', url: 'https://www.deviantart.com', iconPath: `${ICON_DIR}/deviantart.ico` },
  { id: 'srv-57', name: 'Discord', category: 'Messaging', url: 'https://discord.com/app', iconPath: `${ICON_DIR}/discord.ico` },
  { id: 'srv-58', name: 'Disqus', category: 'Media', url: 'https://disqus.com', iconPath: `${ICON_DIR}/disqus.ico` },
  { id: 'srv-59', name: 'Dribbble', category: 'Social', url: 'https://dribbble.com', iconPath: `${ICON_DIR}/dribbble.ico` },
  { id: 'srv-60', name: 'Dropbox', category: 'Productivity', url: 'https://www.dropbox.com', iconPath: `${ICON_DIR}/dropbox.ico` },
  { id: 'srv-61', name: 'Drupal', category: 'Development', url: 'https://www.drupal.org', iconPath: `${ICON_DIR}/drupal.ico` },
  { id: 'srv-62', name: 'Microsoft Edge', category: 'Productivity', url: 'https://www.microsoft.com/edge', iconPath: `${ICON_DIR}/edge.ico` },
  { id: 'srv-63', name: 'Etsy', category: 'Other', url: 'https://www.etsy.com', iconPath: `${ICON_DIR}/etsy.ico` },
  { id: 'srv-64', name: 'Evernote', category: 'Productivity', url: 'https://www.evernote.com', iconPath: `${ICON_DIR}/evernote.ico` },
  { id: 'srv-65', name: 'Facebook', category: 'Social', url: 'https://m.facebook.com', iconPath: `${ICON_DIR}/facebook.ico` },
  { id: 'srv-66', name: 'Messenger', category: 'Messaging', url: 'https://www.messenger.com', iconPath: `${ICON_DIR}/facebook-messanger.ico` },
  { id: 'srv-67', name: 'Firefox', category: 'Productivity', url: 'https://www.mozilla.org/firefox/', iconPath: `${ICON_DIR}/firefox.ico` },
  { id: 'srv-68', name: 'Flickr', category: 'Social', url: 'https://www.flickr.com', iconPath: `${ICON_DIR}/flickr.ico` },
  { id: 'srv-69', name: 'Flipboard', category: 'Media', url: 'https://flipboard.com', iconPath: `${ICON_DIR}/flipboard.ico` },
  { id: 'srv-70', name: 'Foursquare', category: 'Social', url: 'https://foursquare.com', iconPath: `${ICON_DIR}/foursquare.ico` },
  { id: 'srv-71', name: 'GitHub', category: 'Development', url: 'https://github.com', iconPath: `${ICON_DIR}/github.ico` },
  { id: 'srv-72', name: 'GitLab', category: 'Development', url: 'https://gitlab.com', iconPath: `${ICON_DIR}/gitlab.ico` },
  { id: 'srv-73', name: 'Gmail', category: 'Productivity', url: 'https://mail.google.com', iconPath: `${ICON_DIR}/gmail.ico` },
  { id: 'srv-74', name: 'Google', category: 'Productivity', url: 'https://www.google.com', iconPath: `${ICON_DIR}/google.ico` },
  { id: 'srv-75', name: 'Google Drive', category: 'Productivity', url: 'https://drive.google.com', iconPath: `${ICON_DIR}/google-drive.ico` },
  { id: 'srv-76', name: 'Houzz', category: 'Other', url: 'https://www.houzz.com', iconPath: `${ICON_DIR}/houzz.ico` },
  { id: 'srv-77', name: 'HTML5', category: 'Development', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML', iconPath: `${ICON_DIR}/html5.ico` },
  { id: 'srv-78', name: 'HTML5 Box', category: 'Development', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML', iconPath: `${ICON_DIR}/html5-box.ico` },
  { id: 'srv-79', name: 'iCloud', category: 'Productivity', url: 'https://www.icloud.com', iconPath: `${ICON_DIR}/icloud.ico` },
  { id: 'srv-80', name: 'Instagram', category: 'Social', url: 'https://www.instagram.com', iconPath: `${ICON_DIR}/instagram.ico` },
  { id: 'srv-81', name: 'Joomla', category: 'Development', url: 'https://www.joomla.org', iconPath: `${ICON_DIR}/joomla.ico` },
  { id: 'srv-82', name: 'Last.fm', category: 'Media', url: 'https://www.last.fm', iconPath: `${ICON_DIR}/lastfm.ico` },
  { id: 'srv-83', name: 'LinkedIn', category: 'Social', url: 'https://www.linkedin.com', iconPath: `${ICON_DIR}/linkedin.ico` },
  { id: 'srv-84', name: 'Mailchimp', category: 'Productivity', url: 'https://login.mailchimp.com', iconPath: `${ICON_DIR}/mailchimp.ico` },
  { id: 'srv-85', name: 'Mastodon', category: 'Social', url: 'https://mastodon.social', iconPath: `${ICON_DIR}/mastodon.ico` },
  { id: 'srv-86', name: 'Medium', category: 'Media', url: 'https://medium.com', iconPath: `${ICON_DIR}/medium.ico` },
  { id: 'srv-87', name: 'Mix', category: 'Media', url: 'https://mix.com', iconPath: `${ICON_DIR}/mix.ico` },
  { id: 'srv-88', name: 'Myspace', category: 'Social', url: 'https://myspace.com', iconPath: `${ICON_DIR}/myspace.ico` },
  { id: 'srv-89', name: 'Opera', category: 'Productivity', url: 'https://www.opera.com', iconPath: `${ICON_DIR}/opera.ico` },
  { id: 'srv-90', name: 'Shopee', category: 'Marketplace', url: 'https://shopee.co.id', iconPath: `${ICON_DIR}/shopee.ico` }
];